# Quiz Service Configuration - Dev Environment
# dataId: quizsrv.yaml, group: DEFAULT_GROUP, namespace: dev

spring:
  datasource:
    url: jdbc:mysql://localhost:30001/tiz?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2

  data:
    redis:
      host: localhost
      port: 30002
      timeout: 10s

  kafka:
    bootstrap-servers: localhost:30009

# Service URLs (local development)
content:
  service:
    url: http://localhost:8103

llm:
  service:
    url: http://localhost:8106

logging:
  level:
    root: INFO
    io.github.suj1e: DEBUG
