# Chat Service Configuration - Staging Environment
# dataId: chatsrv.yaml, group: DEFAULT_GROUP, namespace: staging

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/tiz?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5

  data:
    redis:
      host: redis
      port: 6379
      timeout: 10s

  kafka:
    bootstrap-servers: kafka:9092

# SSE configuration
sse:
  timeout: 300000

# Service URLs (Docker internal)
llm:
  service:
    url: http://llmsrv:8106

content:
  service:
    url: http://contentsrv:8103

jwt:
  secret: ${JWT_SECRET:TizJwtSecretKey2026VeryLongSecretKeyForSecurity}

logging:
  level:
    root: INFO
    io.github.suj1e: DEBUG
