# Nacos 共享配置 - staging 环境
# dataId: common.yaml, group: DEFAULT_GROUP

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/tiz?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: tiz
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5

  data:
    redis:
      host: redis
      port: 6379
      timeout: 10s

  kafka:
    bootstrap-servers: kafka:9094

logging:
  level:
    root: INFO
    io.github.suj1e: DEBUG
