services:
  llmsrv:
    image: registry.cn-hangzhou.aliyuncs.com/nxo/llmsrv:latest
    pull_policy: always
    container_name: tiz-llmsrv
    restart: always
    ports:
      - "8106:8106"
    environment:
      - NACOS_SERVER_ADDR=${NACOS_SERVER_ADDR:-nacos:8080}
      - NACOS_NAMESPACE=${NACOS_NAMESPACE:-}
    networks:
      - npass
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  npass:
    external: true
