server:
  port: 8101

spring:
  application:
    name: authsrv

  cloud:
    nacos:
      config:
        enabled: false
      discovery:
        enabled: true
        server-addr: ${NACOS_SERVER_ADDR:localhost:30848}
        namespace: ${NACOS_NAMESPACE:}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 1800
  refresh-token-expiration: 604800
