services:
  tiz-web:
    image: registry.cn-hangzhou.aliyuncs.com/nxo/tiz-web:latest
    pull_policy: always
    container_name: tiz-web
    restart: always
    ports:
      - "80:80"
    networks:
      - npass
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  npass:
    external: true
