services:
  tiz-web:
    build:
      context: .
      dockerfile: Dockerfile
    image: registry.cn-hangzhou.aliyuncs.com/nxo/tiz-web:latest
    container_name: tiz-web
    restart: always
    ports:
      - "30000:80"
    networks:
      - npass
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 3s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  npass:
    external: true
