name: tiz_mobile
description: Tiz Mobile MVP
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # Networking
  dio: ^5.4.0
  retrofit: ^4.1.0
  json_annotation: ^4.8.1

  # Routing
  go_router: ^13.1.0

  # Storage
  shared_preferences: ^2.2.2

  # Utils
  uuid: ^4.3.1
  share_plus: ^7.2.1
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.9
  retrofit_generator: ^8.1.0
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
