# Content Service Configuration - Production Environment
# dataId: contentsrv.yaml, group: DEFAULT_GROUP, namespace: prod

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/tiz?useSSL=true&serverTimezone=UTC
    username: ${MYSQL_USER:tiz}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10

  data:
    redis:
      host: redis
      port: 6379
      timeout: 10s

  kafka:
    bootstrap-servers: kafka:9092

# Service URLs (Docker internal)
llm:
  service:
    url: http://llmsrv:8106

logging:
  level:
    root: WARN
    io.github.suj1e: INFO
